### ISSUE TITLE
Implement retrieval of sensor data

### ISSUE THREAD

**Issue by caseycesari** [azavea/ism-watershed-wellness-snapshot#20]
- This card is to take care of the mechanics of retrieving and storing the sensor data.
- Eventually, sensor data is shown on the details screen (#22), but don't worry about wiring this up yet.
- As noted below there are two methods to retrieving real-time sensor data. Try to share as much logic as possible.
- It might make sense to get data when the app is loaded since there is a "last updated" element on the main app page:

![image](https://user-images.githubusercontent.com/1042475/51708725-9393e280-1ff2-11e9-8015-4e3764d31176.png)

**Comment by mmcfarland** [comment]
## Wissahickon
USGS 01474000 Wissahickon Creek at Mouth, Philadelphia, PA
https://nwis.waterdata.usgs.gov/nwis/uv?site_no=01474000

## Tinicum
USGS 01475548 Cobbs Creek at Mt. Moriah Cemetery, Philadelphia
https://nwis.waterdata.usgs.gov/nwis/uv?site_no=01475548

## Delaware Water Gap
USGS 01438500 Delaware River at Montague NJ
https://nwis.waterdata.usgs.gov/nwis/uv?site_no=01438500
Doesn't have real-time feed, but can access Water Quality/Field Samples via endpoints created [here](https://nwis.waterdata.usgs.gov/nwis/qwdata/?site_no=01438500&agency_cd=USGS)

**Comment by fungjj92** [comment]
It looks like we've done this work before in https://github.com/azavea/stormwater-graphql-research/blob/develop/api/src/schema/types/riverGaugeType.js#L207

I'm thinking it makes sense to reuse some of that code. The above implements using`async-await` which is really cool, but is equivalent to using promises in our simple use case.

We can store the data in the redux state so that all components get the signal to update, every 10 minutes, hour or however long it is supposed to be. As for making requests on an interval, the javascript `setInterval` method seems to fit the need --
https://javascript.info/settimeout-setinterval#setinterval

**Comment by caseycesari** [comment]
That sounds good to me. This looks helpful for using async/await with Redux: http://thecodebarbarian.com/async-await-with-react-and-redux-thunk
