### ISSUE TITLE
Check-in on status of site variables, healthy ranges, etc.

### ISSUE THREAD

**Issue by caseycesari** [azavea/ism-watershed-wellness-snapshot#91]

**Comment by dboyer** [comment]
All site variables have been added to https://docs.google.com/spreadsheets/d/19vqjrmnP_Yi9apkNt5R_OGPkYVXOP5fly17vL6aQqjg/edit#gid=0

**Comment by dboyer** [comment]
If the sensor is down, it should leave a message saying "Sorry! Swim back later!"

**Comment by dboyer** [comment]
From the scientists who provided the numbers: "if a number is at the bottom ranges (the lowest 10% of range) or at the highest (top 10% of range) we should consider it "fair"."

**Comment by dboyer** [comment]
The client confirmed they would like to use "Sorry! Swim back later!" if the sensor is down rather than #4 in the already implemented process outlined below.

1) Get up-to-date real time data when available.
2) If data for the current time period isn’t available, use latest available data from the real-time feed
3) If no real time feed exists, or the real time data is older than the quarterly manual data, use the manual data entries.
4) If the manual data isn’t available, or the sensor is completely down, use predefined normal ranges for the data.
